In [4]:
import numpy as np
import copy

# 2d array
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
b = a.copy()
b[0][0] = 100
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[100   2   3]
 [  4   5   6]]
